import { ApiResult } from './../../../../infrastructure/api.result';
export interface ApiResultMyList <mylistEntity> extends ApiResult<{}> {
    Data?: mylistEntity
}

export interface mylistEntity {
    Items?: mylistItems[],
    Pagination?: string,
    TotalCount?: number,
}

export interface mylistItems {
    AcceptDate?: any,
    AcceptPerson?: any,
    Accepted?: boolean,
    AppointmentNo?: string,
    BDCAddress?: any,
    BaseInfoId?: any,
    CanDate?: boolean,
    Canceling?: boolean,
    CancelingTime?: any,
    CasePosition?: any,
    Children?: any,
    CloseDate?: any,
    Closed?: boolean,
    CreateDate?: string,
    FinishDate?: any,
    Finished?: boolean,
    FreezeDate?: any,
    Freezed?: boolean,
    HasChild?: true
    Id?: string,
    IsArchiving?: boolean,
    IsCard?: boolean,
    IsInRsv?: boolean,
    IsPay?: boolean,
    Locked?: boolean,
    MobilePhone?: string,
    MongoId?: string,
    NeedAppend?: boolean,
    NeedPayAmount?: any,
    OsrvModel?: any,
    PDSModel?: any,
    ParentAppointmentId?: any,
    PersonName?: string,
    PersonNo?: string,
    Persons?: any,
    Photos?: any,
    PickedDateIndex?: number,
    PreCheck?: boolean,
    PrintId?: any,
    ProjectName?: string,
    ProjectTypeId?: string,
    QueueIndex?: number,
    Rejected?: boolean,
    ResponseMessage?: any,
    ReturnProjectNo?: any,
    StateCode?: number,
    StateTip?: any,
    TypeCode?: string,
    UnChecked?: boolean,
    UserId?: string,
    locked?: boolean,
    msg?: any,
}